export const errorCodes = Object.freeze({
  // generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  ENCRYPTION_ERROR: 'ENCRYPTION_ERROR',

  // auth (customer JWT verification)
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',

  // service-to-service
  S2S_UNAUTHORIZED: 'S2S_UNAUTHORIZED',

  // wallet domain
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET_ALREADY_EXISTS: 'WALLET_ALREADY_EXISTS',
  WALLET_INACTIVE: 'WALLET_INACTIVE',
  WALLET_CURRENCY_MISMATCH: 'WALLET_CURRENCY_MISMATCH',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  DUPLICATE_REFERENCE: 'DUPLICATE_REFERENCE',
  TRANSFER_SAME_WALLET: 'TRANSFER_SAME_WALLET',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  TRANSFER_NOT_FOUND: 'TRANSFER_NOT_FOUND',
});
